### ISSUE TITLE
Unable to join second node in HA env with v0.11.0-alpha1

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1029]
**Version:**
k3s v0.11.0-alpha1

**Describe the bug**
Unable to join second node to the master in HA env

**To Reproduce**
On master1
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v0.11.0-alpha1 sh -s - server --storage-endpoint='<storage endpoint>'
```
On second node
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v0.11.0-alpha1 sh -s - server --storage-endpoint '<storage endpoint>' --server https://<master>:6443 --token '<token>'
```

**Expected behavior**
kubectl get nodes should display both nodes

**Actual behavior**
kubectl shows only one master

**Additional context**
Log attached
[log1.txt](https://github.com/rancher/k3s/files/3822517/log1.txt)

**Comment by davidnuzik** [comment]
Should be fixed with incoming change that refactors how master bootstrap occurs with external DB.
We should comment in the issue once we have the fix how bootstrapping now works. I believe we will just need to point to the database (`--storage-endpoint`) for each master and that's it. The exception being dqlite which is to be handled/tested separately at a later date.

**Comment by davidnuzik** [comment]
Fixed in latest alpha.

**Comment by ShylajaDevadiga** [comment]
With v0.11.0-alpha2, joining master and worker node was successful.

**Comment by ShylajaDevadiga** [comment]
Closing issue as it is resolved.
