### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by mishushakov** [rancher/k3s#106]
Hey @rancher, many thanks to your contribution to the container and cloud space. Today I found your project via E-Mail from GitHub recommendations. And it really looks like what I was looking for for so many years now.

I'm a life-long Docker and Kubernetes user and I use Raspberry Pi for my workflow very heavily (I develop and deploy micro-services). The problem is, that i never managed to get through Kubernetes installation on my Raspberry. Followed many tutorials and used things like Hypriot OS and so on, but it never worked. I want a software to *just work* with zero configuration and dependencies and your k3s seems very very promising. I would try it out and then get back to you with a user-report (if you want it though), because I'm not much interested in assaulting my Mac's hardware by installing this fat and huge Docker and Kubernetes engine to just test out the images and my deployment configurations. I would like to test it on my Pi.

What I wanted to ask you, whether is this solution a production-ready and can I use it on let's say much more powerful machines? How stable is this? Does it crash occasionally? And it there a way to reduce the RAM and memory footprint even more on a single-node installation? By removing Flannel or kubectl and making them installable through a separate binary? Please let me know. Thank you so much for making this possible ❤️

**Comment by ibuildthecloud** [comment]
@mishushakov I would not say this is production ready.  That is not because we have any indication that it is unstable or buggy.  The only reason I say that this is not production ready is just that this is a very new project.  For due diligence we should really let this bake a bit more.  At the moment is seems to function quite fine.

In terms of scaling there are two possible limitations to scaling.  First is that we do not support an HA installation at the moment.  It is in the works and will be just as simple as the single master, but right now HA is not available, you can only create a high resilient system by backing up and restoring the single master.  Second is that we have not really performance tested the sqlite implementation.  We will try large clusters soon, but it's yet to be tested.  But in theory as k3s matures we expect it to be capable of running clusters in the 100's of nodes.

In terms of making k3s smaller.  We will continue to work in this area.  Right now it's about as small as we reasonably can get it.  You can break out the binaries a bit but you just end up saving maybe 10mb so it wasn't worth the larger binary size for the smaller memory foot print.

**Comment by mishushakov** [comment]
Hey @ibuildthecloud thank you for your kind response! I installed the k3s on my raspberry and it worked like a charm, really easy and it seem to work perfectly fine and at least very reliable! Now it's time to battle-test it. I will spin up some of my containers, they are just compiled binaries (I use and love Go!) and the Dockerfiles are based on `scratch` image. Really interested about the overall performance, but I don't have many expectations there, because you know, Raspberry is a very low-end computer. Thank you for your help and im really excited to watch the project and see where the development of all of this will go

**Comment by mishushakov** [comment]
<img width="682" alt="screenshot 2019-03-01 at 20 53 16" src="https://user-images.githubusercontent.com/10400064/53663201-72638900-3c65-11e9-91b5-97ffe51db05b.png">

**Comment by scofieldpeng** [comment]
How about the HA plan? I really need this for my home k8s cluster...

**Comment by de13** [comment]
@ibuildthecloud what about using dqlite (https://github.com/CanonicalLtd/dqlite) from Canonical?  I know that Rancher and Canonical are used to working together, so it would be a new opportunity to do it again.

**Comment by deniseschannon** [comment]
@scofieldpeng there is a separate issue to make it HA: https://github.com/rancher/k3s/issues/42

@de13 can you file a new issue as a suggestion for using dqlite?
