### ISSUE TITLE
k3s Capabilities.KubeVersion.GitVersion problem

### ISSUE THREAD

**Issue by runningman84** [rancher/k3s#1081]
**Version:**
v1.0.0-rc3

**Describe the bug**
I am trying to install weave-scope in k3s using flux:
```
flux/flux-helm-operator-6cd7ff7d4f-2qptv[flux-helm-operator]: ts=2019-11-14T20:36:12.935259299Z caller=release.go:215 component=release error="Chart release failed: weave-scope: &status.statusError{Code:2, Message:\"validation failed: unable to recognize \\\"\\\": no matches for kind \\\"Deployment\\\" in version \\\"apps/v1beta1\\\"\", Details:[]*any.Any(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}"
```
The problem is that the api version is apps/v1beta1 which is created by this helper script:
https://github.com/helm/charts/blob/master/stable/weave-scope/charts/weave-scope-cluster-agent/templates/_helpers.tpl
Is k3s not compatible with this statement?
semverCompare "<1.14-0" .Capabilities.KubeVersion.GitVersion 

**To Reproduce**
Try to install weave-scope using helm in the latest k3s release (1.0rc...)

**Comment by erikwilson** [comment]
Assuming the semver comparison is coming from https://github.com/Masterminds/sprig, "1.14-0" < "v1.16.2-k3s.1" evaluates correctly. I think a different file may be the culprit tho, as `extensions/v1beta1` would be the bad version used rather than `apps/v1beta1` from the error message. It looks like the error might be coming from here: https://github.com/helm/charts/blob/642a5ebeaf957204e692d329c5ae2d1d9527332d/stable/weave-scope/charts/weave-scope-frontend/templates/deployment.yaml ?

**Comment by runningman84** [comment]
Yes you are right, this has to be fixed in the chart....

**Comment by cjellick** [comment]
Looks like this is resolved, closing
