### ISSUE TITLE
k3s agent service unable to find CA on local host in Oracle VMs

### ISSUE THREAD

**Issue by embcla** [rancher/k3s#1202]
Running k3s version v1.0.0 (18bd921c)

on 4 CentOS 8 guests running inside Oracle VirtualBox.
I created a local network at 10.1.15.0, each VM has 2 network cards one of which is on this specific network. Server is at .1, then nodes 2 to 4 at .2, .3, .4

I deployed root and user keys to all nodes (machines are pingable and ssh-able from one-another) then installed k3s via k3sup (tutorial here https://blog.alexellis.io/create-a-3-node-k3s-cluster-with-k3sup-digitalocean/)

I expected this to be flawless but it is not: no additional node is able to register with the master.
When checking the logs in one of the nodes I see the following line repeating endlessly

`Dec 15 11:58:35 k3s-node-04.local k3s[9478]: time="2019-12-15T11:58:35.361234506+01:00" level=error msg="failed to get CA certs at https://127.0.0.1:40097/cacerts: Get https://127.0.0.1:40097/cacerts: read tcp 127.0.0.1:41514->127.0.0.1:40097: read: connection reset by peer"`

found a reference to this thread
https://github.com/rancher/k3s/issues/484
but it doesn't really tell me if I should fix 127.0.0.1  pointing it to the master, to a real CA, and how to do it. Moreover why wouldn't the master have a problem with the CA while the nodes do? they are the same basic VM

what am I missing?

**Comment by erikwilson** [comment]
CentOS 8 like RHEL 8 is maybe not well supported by kubernetes (iptables should be legacy mode).

For testing I use a similar setup (except with Alpine and Vagrant), for machines with multiple network devices it may help to set `--flannel-iface` to the device used to communicate between nodes. Also make sure that you can curl the server url, it should be of the form 'https://server-ip:6443', where the port (6443) is important. It might also be worth checking if a firewall is causing the problem.

**Comment by embcla** [comment]
Thanks Erik

I will try your suggestions and report back.

Regarding the warning about iptables it confused me: I'm used to see such
warnings when you're running an old version, and given the pace at which
RHEL moves I'm more used to that so seeing a warning about a version that
is much too new was somewhat baffling. Like can I even downgrade or would
it break some functionality?

In one of my jobs I've extensively employed CentOS for stable backends
deployments at clients. Given that k3s is aimed at stability and edge, what
ditros are being employed in these scenarios? Of course I can fire up
Ubuntu, it's just that it doesn't seem a sensible business choice.

Thanks


Claudio
---
Written on the back of my snow owl while flying inverted through Manhattan,
some grammar might be off too

**Comment by erikwilson** [comment]
The iptables issue irks me @embcla, I blame iptables for putting themselves in this situation and RHEL/CentOS for just ignoring it. On most systems you can downgrade to use legacy iptables, but as far as I know that is not possible on version RHEL 8 (disclaimer: I have not tried). The fix is to migrate all projects to have a dual iptables stack where they try new iptables/nftables first then legacy iptables binaries. We can fix it for k3s without too much trouble, but a lot of other projects that depend on or use k3s/k8s would still fail until they support both.

**Comment by embcla** [comment]
Dropping this. Using Ubuntu 18.04 instead

**Comment by rlabrecque** [comment]
I was hitting this on k3s 1.18, ubuntu 18.04 running in as high-availability in AWS.

I couldn't access the servers via my NLB with curl from the agents such as: `curl https://k3s.internal.mydomain.com:6443`. So I attempted to fix that by fixing my NLB to be accessible from my private subnets and used `Scheme: 'internal'` instead of `Scheme: 'internet-facing'` on the NLB.

Recreating the stack with just this change fixed it for me 👍
