### ISSUE TITLE
Formally add support for SELinux (Enforced mode)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#1372]
We need to expand our **testing** and identify any issues that prevent us from formally supporting SELinux (in enforced mode) on CentOS. Please note that SELinux is expected to work -- this issue is for tracking testing effort so we can formally support it.

We should review existing GitHub issues, but we need to execute some testing and identify any other issues. As needed, we'll need to resolve these issues so we may fully support SELinux on CentOS.

Formal CentOS (general OS) support is also needed, which is tracked separately here: https://github.com/rancher/k3s/issues/1371

**Comment by davidnuzik** [comment]
@ShylajaDevadiga I have assigned this issue to you for now. This will require some testing and discovery. We need to identify any/all SELinux CentOS issues that prevent us from formally supporting CentOS with SELinux support in our next release. Work with me as needed.

**Comment by davidnuzik** [comment]
As a reminder we must support IPv6 as well.

**Comment by westurner** [comment]
- https://wiki.centos.org/HowTos/SELinux#Troubleshooting_SELinux
- https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security-enhanced_linux/sect-security-enhanced_linux-fixing_problems-allowing_access_audit2allow
  - https://danwalsh.livejournal.com/24750.html
- https://stopdisablingselinux.com/

Is this more complicated than running tests in permissive mode, running audit2allow, and reviewing the generated policy for what needs to be relabled so that k3s will run with selinux in enforcing mode?

- https://www.google.com/search?q=openshift+selinux
  - https://fedorapeople.org/~dwalsh/SELinux/Presentations/openshift_selinux.ogv
  - https://blog.openshift.com/openshift-protects-against-nasty-container-exploit/
  - https://blog.openshift.com/securing-kubernetes/

**Comment by westurner** [comment]
- [ ] remove the "Set SELinux to disabled state" task from the ansible prereq role: https://github.com/rancher/k3s/blob/0374c4f63d056df01c3e9e8cf4d77a6461169070/contrib/ansible/roles/prereq/tasks/main.yml#L2-L5

**Comment by cjellick** [comment]
@westurner the main bit of work involves getting MCS label support into containerd (k3s's embedded contianer runtime): See this WIP PR from @ibuildthecloud:
https://github.com/containerd/cri/pull/1246

**Comment by erikwilson** [comment]
Merged #1448

**Comment by davidnuzik** [comment]
Closing this issue in favor of https://github.com/rancher/k3s/issues/533
