### ISSUE TITLE
Display tokens/credentials for basic authentication?

### ISSUE THREAD

**Issue by southwolf** [rancher/k3s#140]
**Is your feature request related to a problem? Please describe.**

K3s created a `passwd` file by

```
--basic-auth-file /var/lib/rancher/k3s/server/cred/passwd 
```
 The passwords are just randomly generated [see code](https://github.com/rancher/k3s/blob/master/pkg/daemons/control/server.go#L357-L368)

and never displayed, no one can connect to the API using **basic auth** even if it's already set

**Describe the solution you'd like**

Display the passwords in setup logs

**Describe alternatives you've considered**

Let user input the password, if not, generate one.

**Comment by ibuildthecloud** [comment]
When the server starts is always outputs a kubeconfig at `/etc/rancher/k3s/k3s.yaml` or where you configure it to with `--write-kubeconfig ...`.  In that file it uses basic auth.  For example

```yaml
users:
- name: default
  user:
    password: a36b883d48d0298713d009a2e9261378
    username: admin
```

We do purposely avoid printing any credentials in the logs or output because most people consider that a security issue.  But in general the idea is you clients should just use the kubeconfig that is generated.  And also the credential is random only on the first start.  After that it won't change it.

**Comment by southwolf** [comment]
@ibuildthecloud Thanks for the notice! I forgot to look into the kubeconfig. Mea culpa! Closing this issue.
