### ISSUE TITLE
Deterministic cni-bin-dir 

### ISSUE THREAD

**Issue by marshallford** [rancher/k3s#1434]
**Is your feature request related to a problem? Please describe.**

[Istio CNI](https://istio.io/docs/setup/additional-setup/cni/) requires that you point it at the `cniBinDir` and `cniConfDir` used by k8s CNI. Out of the box k3s has a well known `cni-conf-dir` but the bin directory is based a random uuid.

**Describe the solution you'd like**

The ability to pass a value that replaces the uuid.

**Describe alternatives you've considered**

Manually create a symlink from `/var/lib/rancher/k3s/data/some-value/bin` to some well known path like `/opt/cni/bin` after installing k3s.

**Additional context**

**Comment by marshallford** [comment]
When pointing Istio CNI at a symlink path or the uuid path I am still running into issues with injected pods not spinning up correctly: `failed to setup network for sandbox`. I tried using Calico instead of Flannel with k3s as well.

**Comment by marshallford** [comment]
A few FYIs for anyone that stumbles onto this issue: 

1. It appears that k3s is exposing the standard CNI host paths to containers (some how?). As a result you can point at the standard directories when installing Istio CNI (`/opt/cni/bin`, `/etc/cni/net.d`). No symlinks required. I only validated this with Calico.

2. When using k3s + baked in Flannel or k3s + Calico I was still getting the following error with Istio 1.5.1 and k3s v1.17.4+k3s1:

```
Events:
  Type     Reason                  Age                    From                 Message
  ----     ------                  ----                   ----                 -------
  Warning  FailedCreatePodSandBox  3m26s (x5578 over 8h)  kubelet, ubuntu.lan  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "85ed05f40551b503a12cbf25c9be3ec7f296c34a836f3b65491e9e1d15d647ea": exit status 1
```

3. From what I gather the above issue is with the embedded version of containerd and not with Kubernetes part of the k3s codebase. I **was** able to get k3s + Calico + Istio CNI working by installing an alternate CRI. I used cri-o: `--container-runtime-endpoint unix:///var/run/crio/crio.sock`. For those looking to follow along I did have to change `cgroup_manager` from `systemd` to `cgroupfs` in `/etc/crio/crio.conf`. YRMV.

**Comment by izhigalko** [comment]
@marshallford I found why istio-cni process exits with status 1.

The problem is that busybox nsenter command doesn't recognize arguments properly:
`{"level":"info","time":"2020-05-15T14:35:34.504810Z","msg":"Pod proxy-app-5d5fb7c7c8-44gnt contains inject annotation: true"}
{"level":"info","time":"2020-05-15T14:35:34.504826Z","msg":"setting up redirect"}
{"level":"info","time":"2020-05-15T14:35:34.504845Z","msg":"Redirect local ports: *"}
{"level":"info","time":"2020-05-15T14:35:34.504875Z","msg":"nsenter args","nsenterArgs":["--net=/var/run/netns/cni-7306da4e-681f-553a-9b76-a4192f1d1996","/bin/istio-iptables.sh","-p","15001","-u","1337","-m","REDIRECT","-i","*","-b","*","
-d","15020,15090","-o","15020","-x","","-k",""]}
{"level":"error","time":"2020-05-15T14:35:34.507394Z","msg":"nsenter failed","out":"nsenter: unrecognized option: b\nBusyBox v1.29.3 (2019-10-04 00:00:31 UTC) multi-call binary.\n\nUsage: nsenter [OPTIONS] [PROG [ARGS]]\n\n\t-t PID\t\tTar
get process to get namespaces from\n\t-m[FILE]\tEnter mount namespace\n\t-u[FILE]\tEnter UTS namespace (hostname etc)\n\t-i[FILE]\tEnter System V IPC namespace\n\t-n[FILE]\tEnter network namespace\n\t-p[FILE]\tEnter pid namespace\n\t-U[FI
LE]\tEnter user namespace\n\t-S UID\t\tSet uid in entered namespace\n\t-G GID\t\tSet gid in entered namespace\n\t--preserve-credentials\tDon't touch uids or gids\n\t-r[DIR]\t\tSet root directory\n\t-w[DIR]\t\tSet working directory\n\t-F\t
\tDon't fork before exec'ing PROG\n","error":"exit status 1"}`

**Comment by brandond** [comment]
Yay, more k3s-root BusyBox compat issues.

**Comment by marshallford** [comment]
@izhigalko Nice find! Is that from the istio-cni pod logs or k3s logs? I remember the istio-cni pods passing the readiness and liveness checks (the pods were marked as running).

**Comment by izhigalko** [comment]
@marshallford I found this in containerd log with CONTAINERD_LOG_LEVEL environment variable set to debug.

**Comment by brandond** [comment]
Just out of curiosity, can you try this to use the host nsenter instead of busybox:

`sudo find /var/lib/rancher/k3s/data -mindepth 1 -maxdepth 1 -type d -exec ln -sf `which nsenter` {}/bin/nsenter \;`

**Comment by izhigalko** [comment]
@brandond sorry for long answer. I ran K3S inside docker and there is no /var/lib/rancher/k3s/data directory inside container. 

But I mounted another nsenter version inside container and I have another error:

`nsenter: failed to execute sh /bin/istio-iptables.sh: No such file or directory`

I don't have enough time to debug it. I'll do it another time.
