### ISSUE TITLE
Improve ansible scripts

### ISSUE THREAD

**Issue by cjellick** [rancher/k3s#1488]
The example inventory should be placed into a subdirectory much like kubespray does it.
That way the group_vars for all are not overwritten by default.
This enables having this repo as a git submodule without having to modify all.yml.

Additionally, extra_server_args can be specified (useful for --no-deploy traefik for instance)

This is a tracking issue for https://github.com/rancher/k3s/pull/1429

**Comment by cjellick** [comment]
also https://github.com/rancher/k3s/pull/1472 - Add Type/TimeoutStartSec/ExecStartPre to ansible systemd unit files similar to ones created by install.sh

**Comment by serverbaboon** [comment]
I started an project for a raspberry pi Ansible deploy before I realised there was already some Ansible code in the k3s repo. Its probably too specific for use for a pr and its a learning exercise for me so code quality maybe another issue,  but I have done some work around submitting arguments to the service files etc that maybe of some use? I have also done some work around external databases

It does not follow the best practices for layout that you mention (yet)

https://github.com/serverbaboon/ansible-k3s

**Comment by davidnuzik** [comment]
@St0rmingBr4in could you take a look at this to validate?

**Comment by St0rmingBr4in** [comment]
Just to be sure, you want me to validate that the playbook still works with v1.18.2-rc1+k3s1 right ?

**Comment by davidnuzik** [comment]
Basically yes @St0rmingBr4in 
If you don't mind taking the time to briefly test it out. We don't have many free cycles with QA at the moment.

**Comment by St0rmingBr4in** [comment]
Okay, I'll test it out ☺️

**Comment by davidnuzik** [comment]
Hi @St0rmingBr4in I don't want to put any pressure on you, but any updates?
If we don't hear back we may close the issue as this is all merged in and ready for v1.18.2+k3s1 release which will be coming out soon. No worries if you don't have cycles to test this as the change is low impact.

**Comment by St0rmingBr4in** [comment]
Hi,
Here are the tests I ran: (All the tests where done on x64)

On vagrant box "debian/stretch64"
 - The playbook works fine as is.

On vagrant box "bento/centos-7.6"
 - I had the issue #360 since TimeoutStartSec was not edited in the playbook in the fix #365. Thus I opened a PR  #1717
 - I needed to modprobe `br_netfilter` and add `/usr/local/bin` to sudo secure_path so I modified the playbook: #1718

The 2 issues with Centos were also present when running with `v1.17.2+k3s1` so I don't think it is related to running `v1.18.2-rc2+k3s1`
