### ISSUE TITLE
In a multi server cluster rebooted node is unschedulable.

### ISSUE THREAD

**Issue by ShylajaDevadiga** [rancher/k3s#1521]
**Version:**
k3s version v1.17.3-alpha1+k3s1

**Describe the bug**
In a multi master cluster with external db, node after reboot stays in NotReady state,
Node is not schedulable
Node is able to communicate to the apiserver
This behavior is seen in mysql and postgres as datastore backend

**To Reproduce**
Create a cluster with 3 master nodes.
Verify all nodes are schedulable
Reboot one master node
Schedule some job after reboot
Node is in NotReady state and is unschedulable

**Expected behavior**
All nodes should be in Ready state

**Actual behavior**
Rebooted node is in NotReady State.
```root@ip-172-31-3-204:~# kubectl get node 
NAME               STATUS     ROLES    AGE   VERSION
ip-172-31-3-204    NotReady   master   65m   v1.17.3-alpha1+k3s1
ip-172-31-9-159    Ready      master   55m   v1.17.3-alpha1+k3s1
```

**Comment by brandond** [comment]
logs?

**Comment by ShylajaDevadiga** [comment]
I've deleted the setup @brandond but issue is reproducible.

**Comment by galal-hussein** [comment]
After shutting down the node and starting it back up it changes its public IP on AWS and since the automation scripts uses the flag --node-external-ip <public-ip> it doesn't get updated and this reflects on the kubernetes service endpoints:

```
root@ip-172-31-15-171:~# kubectl get endpoints
NAME         ENDPOINTS                                               AGE
kubernetes   13.58.45.254:6443,18.219.119.73:6443,3.136.17.12:6443   37m
```
To fix the issue, after each reboot the --node-external-ip flag needs to be updated:

1- update the --node-external-ip flag in the file:
```
/etc/systemd/system/k3s.service
```
2- do `systemctl daemon-reload`
3- restart k3s
```
systemctl restart k3s
```
Wait for the server to be in a Ready state again

**Comment by brandond** [comment]
alternately you could assign a static Elastic IP to it so that the external IP doesn't change when you stop and start it.

**Comment by ShylajaDevadiga** [comment]
Updating the node-external-ip to newly set ip resolves the issue.
