### ISSUE TITLE
x509 client certificate authentication for default admin account

### ISSUE THREAD

**Issue by nicklasfrahm** [rancher/k3s#1616]
**Is your feature request related to a problem? Please describe.**
I am concerned about the security of my installation, because the default user of every **K3S** installation is the user `admin`. The only required credential is a hexadecimal password. I am concerned about brute-force attacks, when exposing the Kubernetes API via a public IP.

**Describe the solution you'd like**
x509 client certificate authentication for the default admin user. It should not be possible by default to use basic auth for the API server or there should be an option to select the authentication method.

I like the way, Rancher's **RKE** does create a `kubeconfig.yml`, where the admin is authenticated via a a client certificate, so why does **K3S** not do this?

Other than this, I really love this project and want to show my appreciation to the contributors, keep up the good work! ❤️

**Comment by davidnuzik** [comment]
Being done as a pre-req for RKE2 initial release.

**Comment by davidnuzik** [comment]
Resolved in https://github.com/rancher/k3s/pull/1704

**Comment by rancher-max** [comment]
#### Validated using latest master commit: `f72d39ad9cced43f61506f2a66e63031a0ee2072`

- Simple install validated is using `curl -sfL https://get.k3s.io | INSTALL_K3S_COMMIT=f72d39ad9cced43f61506f2a66e63031a0ee2072 sh -`
  - `sudo cat /etc/rancher/k3s/k3s.yaml` shows user with `client-certificate-data` and `client-key-data` values instead of `username` and `password`
- Validated HA setup and accessing the cluster externally

**Comment by chauffer** [comment]
`curl -sfL https://get.k3s.io/ | sh -s - --disable=traefik` as of today still results in an user being created:

```
:~# grep password: /etc/rancher/k3s/k3s.yaml -C3
users:
- name: default
  user:
    password: snip
    username: admin
:~# 
```

**Comment by sraillard** [comment]
In the release notes of the 1.19 version, it should have been great to have this change documented as we were using password access and that is breaking some scripts we had.

**Comment by cjellick** [comment]
You're right. This change is present in the [upstream release notes for 1.19](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#no-really-you-must-read-this-before-you-upgrade) (which necessitated this change in k3s), but it should have build called out explicitly in our release notes as well. It is a miss on our part.

Would you mind giving a little more detail on the usecase that broke so that I can better understand?

**Comment by sraillard** [comment]
I had an explanation from @brandond in the issue #2342 that I have opened. This is for edge computing cases where you have industrial server on the field for many years. We had already experienced the expired certificates issue for server running more than 10 years, so with a default admin certificate valid only for 1 year, this is very risky!
