### ISSUE TITLE
Any way to speed up pod eviction and scheduling

### ISSUE THREAD

**Issue by samirsss** [rancher/k3s#1843]
**Is your feature request related to a problem? Please describe.**
We're deploying k3s on a 2 node cluster, using mariadb at the moment and to achieve some form of HA (not a hitless HA at the moment). Both the nodes are master nodes. 

When a node (which is labeled as the active) goes down we want to drain it quickly and get 1 pod (database) to switch over to the other node. We've already implemented service dependency scripts to do this when we detect k3s is going down. Its not quick enough and typically times out. 

What that does is delays the pod eviction and re-spawning of the pod on the new active node. Which is our current issue. 

**Describe the solution you'd like**
I'd like to get some feedback from experts on what we could do (as part of k3s server setup) in this particular type of deployment to evict the pods faster and also schedule certain pods quicker.

I've already assigned priorities for the DB pod way higher than other pods, like so

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority

We're also using the PodDisruptionBudget to see if that helps:
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: db-pdb
spec:

What i am looking for is any possible tweaks that we can do using --kub-scheduler-args or any recommendations on how to ensure that this 1 particular Statefulset is scheduled faster and evicted faster.

**Comment by brandond** [comment]
Are you saying that the pod takes too long to stop when you're draining the node prior to shutdown? 

All that draining does is cordon the node and then evicts (deletes) all the pods so that they're recreated on the other node. The deletion process waits for normal process termination, up to the `terminationGracePeriodSeconds`. Once it's terminated then a new pod can be created on the other node. The best way to make this happen quickly is to ensure that the database shuts down as fast as possible.

FWIW, there does not appear to be any particular logic around ordering pods during drain, so if you have a pod you want evicted first you should do that manually:
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/kubectl/pkg/drain/drain.go#L181

Are you seeing something else, or trying to handle a case where the node has gone down without being drained?

**Comment by samirsss** [comment]
@brandond thanks for the suggestions. I'm going to try out the terminationGracePeriodSeconds settings to see if that helps.

Also will try and see if i can evict the db pod first.
