### ISSUE TITLE
k3s on Android

### ISSUE THREAD

**Issue by seiyaa** [rancher/k3s#191]
I run k3s on Android, and get the following tip:
Failed to find memory cgroup, you may need to add "cgroup_memory=1 cgroup_enable=memory" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"

lowmemorykiller is used for memory control on Android, cgroup memory is disable on Android

how can I run k3s on Android?
1.enable cgroup memory on Android?
2.remove the following code, and compile k3s?
if !strings.Contains(string(cgroups), "memory") {
		msg := "ailed to find memory cgroup, you may need to add \"cgroup_memory=1 cgroup_enable=memory\" to your linux cmdline (/boot/cmdline.txt on a Raspberry Pi)"
		logrus.Error("F" + msg)
		return errors.New("f" + msg)
} 

which is the better way?

**Comment by erikwilson** [comment]
I am interested in this also, in case you haven't seen the PR: https://github.com/rancher/k3s/pull/195

Hopefully it will be easier to run as user in the near future, at the moment it may require a rooted device, custom kernel, or an emulation app.

**Comment by AkihiroSuda** [comment]
Just curious, what is the motivation for running k3s on Android?

**Comment by AkihiroSuda** [comment]
Anyway, I don't think it works on Android, as Android kernel is likely to be compiled without support for user namespaces.

**Comment by erikwilson** [comment]
My interest is mostly because it is a fairly capable and expensive arm64 device that I cary with me everywhere, so for testing out arm builds it would be convenient. 

Probably not great for battery, but I could see building a cluster or iot gateways out of old phones as a good way to reuse them rather than recycling or just sending to a landfill, at that point you are probably using your own kernel tho.

**Comment by nofearOnline** [comment]
@erikwilson Hi, did you success in setting a k3s cluster  on an Android device/s?
