### ISSUE TITLE
race when unpacking data-dir can cause segfaults

### ISSUE THREAD

**Issue by dweomer** [rancher/k3s#1938]
**Version:**
v1.16.x / v1.17.x / v1.18.x on arm/arm64/amd64

**K3s arguments:**

`k3s server`

**Describe the bug**

There is a race when invoking `kubectl` before `k3s server` has unpacked the data-dir which will sometimes result in segfaults until the data-dir is deleted and `k3s server` started again.

**To Reproduce**

Start `k3s server` and immediately go into tight loop querying "cluster" status via `kubectl get`

**Expected behavior**

Neither `k3s server` nor `kubectl get node -o wide` segfault.

**Actual behavior**

Typically, `k3s server` will segfault and go into restart loop.

**Additional context / logs**

The bug looks to be caused by the extract code using a determinant, derivative temporary location for unpacking the data-dir: https://github.com/rancher/k3s/blob/v1.18.4+k3s1/cmd/k3s/main.go#L132-L141

**Comment by dweomer** [comment]
This should be fixed but longer term maybe it would be good to have an integrity check on the unpacked data-dir at invocation of k3s-server and k3s-agent? Checking every invocation of the multi-call would probably be excessive. This would make tampering with the data-dir ephemeral in that it would get wiped out prior to the k3s agent running (or it would fail to run ... which is what currently happens on an inconsistent basis).

**Comment by dweomer** [comment]
Sorry, poor wording. "This should be fixed" != "someone fixed this" in this instance, it means we should fix it.

**Comment by erikwilson** [comment]
Ah, good point and thanks for linking to the other issue, this is likely the cause.

Should be a very simple fix, instead of setting tempDest to `dir + "-tmp"` should be something like `dir + "-tmp-" + randomId`. Changing contents of the data dir can be useful for some developer edge cases.

**Comment by erikwilson** [comment]
We should probably be checking the shasum just after extracting tho, that would also defeat the race condition. 

By removing the existing tempDest we assume it is stale, that might be possible if it got a SIGKILL but typically it means there is something else trying to extract it. Instead of removing tempDest we could instead return an error that indicates you need to wait for extraction to complete or manually remove the directory.

It might also be helpful to have the install script perform an operation which will cause the extraction before starting the service.

**Comment by erikwilson** [comment]
Decided to go with a file lock on the data directory and verification immediately after untar, as that seems simple & the least error prone.

**Comment by ShylajaDevadiga** [comment]
Validated fix using k3s commit id 6b11d86. Related issue #2298
