### ISSUE TITLE
RHEL8 Support

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2184]
Support RHEL8, like we do currently in rancher/rke2. This includes selinux policy RPM for el8.

**Comment by cjellick** [comment]
The k3s code base functionally supports RHEL/CentOS 8 now. The big lift was to get it supporting nftables and that work is done.
However, we need to revisit the RPM packaging for k3s and the associated selinux policies.

We've run out of time accomplish this in our initial 1.19 release, but will tackle it in the 1.19 patch cycle.

**Comment by Oats87** [comment]
Work is waiting on: https://github.com/rancherlabs/eio/issues/268 so that the `k3s-selinux` repository can be augmented to publish in a similar manner to the way we publish `rke2-selinux` rpms

**Comment by davidnuzik** [comment]
@Oats87 any updates on this? The EIO issue appears to be resolved.

**Comment by Oats87** [comment]
@davidnuzik https://github.com/rancher/k3s-selinux/pull/12 is the PR that contains the work necessary to build el7_8 rpms for k3s

**Comment by davidnuzik** [comment]
@Oats87 Is more work needed? I didn't see this in to test so it didn't get tested for the patches that just went out.

**Comment by Oats87** [comment]
@davidnuzik This is not ready yet, pending a decision on how we will handle the RPM installation for k3s-selinux as it no longer lives in the root of the `rpm.rancher.io` repository

**Comment by davidnuzik** [comment]
Thanks @Oats87

**Comment by Oats87** [comment]
Once https://github.com/rancher/k3s/pull/2408 is merged, this can be verified by attempting to install K3s on an EL7/EL8 system that falls into the following:

RHEL 7
RHEL 8
CentOS 7
CentOS 8
Oracle Linux 7
Oracle Linux 8

This should be checked through:

INSTALL_K3S_CHANNEL=testing ./install.sh which will install K3s using the testing channel

INSTALL_K3S_CHANNEL=testing INSTALL_K3S_SKIP_SELINUX_RPM=true ./install.sh which will install K3s but fail out because the K3s selinux RPM needs to be "manually" installed". Can be useful for things like airgap.

For now, this will only work on the testing channel until we verify that the k3s-selinux rpm changes are valid and can be cut into stable and latest.

**Comment by Oats87** [comment]
This is ready for test, but is *not* merged to master yet as once merged, it will change `get.k3s.io` 

I've gone ahead and smoke tested this myself in the following scenarios:

RHEL 7
RHEL 8

CentOS 7
CentOS 8

and corresponding upgrades from the "old" `install.sh` to the latest one

**Comment by ShylajaDevadiga** [comment]
On CentOS 7/ RHEL 7 Validated install and uninstall script successfully with selinux enabled/disabled. 
Cluster is up, validated as per test plan

On CentOS 8/RHEL 8 with selinux disabled install, uninstall is validated.
On CentOS 8/RHEL 8 with selinux enabled svclb crashloops. Issue tracked here #2424
