### ISSUE TITLE
[Documentation] experimental etcd snapshot/restore procedure

### ISSUE THREAD

**Issue by davidnuzik** [rancher/k3s#2224]
K3s v1.19.1+k3s1 release will include [etcd snapshot and restore](https://github.com/rancher/k3s/pull/2154). Similar to [embedded etcd](https://github.com/rancher/k3s/pull/1770), this will be _experimental_ in this release. We will plan in the next patch release or two to fully support both of these new features.

The [etcd snapshot and restore](https://github.com/rancher/k3s/pull/2154) PR does a good job outlining the new flags this feature adds. It talks about how it can be leveraged. @rancher-max has been testing this and may be able to provide additional context as well if he is needed.

**Comment by rancher-max** [comment]
- The correct list of potentially relevant flags are:
```
   --datastore-endpoint value                 (db) Specify etcd, Mysql, Postgres, or Sqlite (default) data source name [$K3S_DATASTORE_ENDPOINT]
   --datastore-cafile value                   (db) TLS Certificate Authority file used to secure datastore backend communication [$K3S_DATASTORE_CAFILE]
   --datastore-certfile value                 (db) TLS certification file used to secure datastore backend communication [$K3S_DATASTORE_CERTFILE]
   --datastore-keyfile value                  (db) TLS key file used to secure datastore backend communication [$K3S_DATASTORE_KEYFILE]
   --etcd-disable-snapshots                   (db) Disable automatic etcd snapshots
   --etcd-snapshot-schedule-cron value        (db) Snapshot interval time in cron spec. eg. every 5 hours '* */5 * * *' (default: "0 */12 * * *")
   --etcd-snapshot-retention value            (db) Number of snapshots to retain (default: 5)
   --etcd-snapshot-dir value                  (db) Directory to save db snapshots. (Default location: ${data-dir}/db/snapshots)

   --cluster-init                             (experimental/cluster) Initialize a new cluster [$K3S_CLUSTER_INIT]
   --cluster-reset                            (experimental/cluster) Forget all peers and become sole member of a new cluster [$K3S_CLUSTER_RESET]
   --cluster-reset-restore-path value         (db) Path to snapshot file to be restored
```
- Bringing up a cluster using `--cluster-init` defaults to using embedded etcd, so it is not required to pass `--datastore-endpoint etcd`.
- I recommend using the `/etc/rancher/k3s/config.yaml` when setting these configurations, especially if wanting to pass a different cron value. I have been unable to successfully pass that flag in the arguments to `INSTALL_K3S_EXEC` due to improper escape sequences with asterisks. Even when I thought I escaped it properly, I didn't see it using the cron value I chose. There are probably plenty of users better with bash or using a different OS (I used Ubuntu 20.04) where this will work, but it is much easier using config.yaml
- Using `--cluster-reset` is essentially a two step process:
  1. Restart the cluster using the cluster-reset flag (and optionally the restore-path to restore from a snapshot)
  2. This should fail to start and give a message in the logs saying it can be restarted without that flag now, so remove both of the flags and start k3s again. It should run successfully (and be restored from the snapshot specified, if any).

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2684 was merged
