### ISSUE TITLE
[QUESTION] - override ds.podSandboxImage

### ISSUE THREAD

**Issue by normander** [rancher/k3s#282]
Hi,

how can I override ds.podSandboxImage for my own in my registry without build again?

**Comment by ibuildthecloud** [comment]
Not currently supported... sorry.  With the offline support in v0.3.0 you can preload the pause image on the nodes and that could allow you to choose whatever image you want.

The intention is to add a generic hook so that people can customize whatever flag in k8s components (like kubelet).  We just haven't done that yet.

**Comment by normander** [comment]
Is there any chance to build my own k3s with pause image from private registry? How can I achieve this?
