### ISSUE TITLE
0.6.0 - Missing advise how to install the metrics server

### ISSUE THREAD

**Issue by giminni** [rancher/k3s#557]
**Describe the bug**
According to the project log the recipe for the metrics server was deleted yesterday, and it is unclear how to enable the metrics server for top and hap on 0.6.0. After executing kubectl top node I get a weird error telling me that heapster is missing?

**To Reproduce**
```bash
sudo kubectl top node
```
**Expected behavior**
A list of installed nodes with metrics information

**Additional context**

```bash
Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)
```

**Comment by erikwilson** [comment]
The metrics-server recipe was removed because the modification to the metrics-server deployment to use insecure TLS and internal IPs for communication are no longer needed. Some changes were introduced so that CoreDNS provides an IP for the hostname and necessary certs use a SAN with that hostname. 

The metrics server has always required manual installation, the difference now being that you should install from the official repo: https://github.com/kubernetes-incubator/metrics-server

**Comment by erikwilson** [comment]
Thanks for filing this issue @giminni! I have updated the documentation and opened another issue #560 for resolving the caveats in the docs and making the process easier.
