### ISSUE TITLE
install scripts stops after downloading hash

### ISSUE THREAD

**Issue by gosuri** [rancher/k3s#937]
**Version:**
0.10.0

Provide the output from `k3s -v` and provide the flags used to install or run k3s server.

**Describe the bug**

install script stops after 3 lines:
```
[INFO]  Finding latest release
[INFO]  Using v0.10.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.0/sha256sum-amd64.txt
```

**To Reproduce**

```
ssh root@node2
curl -sfL https://get.k3s.io | sh -
```

**Expected behavior**
Install kubernetes

**Actual behavior**

doesn't install kubernetes

**Additional context**

**Comment by erikwilson** [comment]
Sorry there was an issue @gosuri, the script may have failed from a temporary github issue or there may be an issue where a disk is full or a portion of the disk not writable. Checking `df -h` may help, if you can please provide more info on the OS and type of system, disk usage, etc.

**Comment by MatthieuCutin** [comment]
I'm facing an issue quite similar but more verbose, install script fail with this output :

`curl -sfL https://get.k3s.io | sh -
[INFO]  Finding latest release
[INFO]  Using v0.10.0 as release
[INFO]  Downloading hash https://github.com/rancher/k3s/releases/download/v0.10.0/sha256sum-arm.txt
[INFO]  Downloading binary https://github.com/rancher/k3s/releases/download/v0.10.0/k3s-armhf
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.`

`systemctl status k3s.service
● k3s.service - Lightweight Kubernetes
   Loaded: loaded (/etc/systemd/system/k3s.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-10-23 13:38:32 CEST; 2s ago
     Docs: https://k3s.io
  Process: 31488 ExecStart=/usr/local/bin/k3s server (code=exited, status=1/FAILURE)
  Process: 31485 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
  Process: 31479 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
 Main PID: 31488 (code=exited, status=1/FAILURE)
      CPU: 16.602s

oct. 23 13:38:32 raspberrypi systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
oct. 23 13:38:32 raspberrypi systemd[1]: Failed to start Lightweight Kubernetes.
oct. 23 13:38:32 raspberrypi systemd[1]: k3s.service: Unit entered failed state.
oct. 23 13:38:32 raspberrypi systemd[1]: k3s.service: Failed with result 'exit-code'.`

`journalctl -xe
-- L'unité (unit) k3s.service a commencé à démarrer.
oct. 23 13:39:16 raspberrypi k3s[31797]: time="2019-10-23T13:39:16.519902822+02:00" level=info msg="Starting k3s v0.10.0 (f9888ca3)"
oct. 23 13:39:16 raspberrypi k3s[31797]: time="2019-10-23T13:39:16.530857013+02:00" level=info msg="Kine listening on unix://kine.sock"
oct. 23 13:39:16 raspberrypi k3s[31797]: time="2019-10-23T13:39:16.533918047+02:00" level=info msg="Fetching bootstrap data from etcd"
oct. 23 13:39:16 raspberrypi k3s[31797]: time="2019-10-23T13:39:16.566092445+02:00" level=info msg="Running kube-apiserver --advertise-port=6443 --allow-privileged=true --anonymous-auth=false --api-audien
oct. 23 13:39:16 raspberrypi k3s[31797]: Flag --basic-auth-file has been deprecated, Basic authentication mode is deprecated and will be removed in a future release. It is not recommended for production e
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.570043   31797 server.go:650] external host was not specified, using 192.168.1.2
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.572772   31797 server.go:162] Version: v1.16.2-k3s.1
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.606663   31797 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,Servic
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.607022   31797 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.612320   31797 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,Servic
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.612429   31797 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.745042   31797 master.go:259] Using reconciler: lease
oct. 23 13:39:16 raspberrypi k3s[31797]: I1023 13:39:16.896715   31797 rest.go:115] the default service ipfamily for this cluster is: IPv4
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.438856   31797 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.550480   31797 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.668387   31797 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.689900   31797 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.762439   31797 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.883793   31797 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: W1023 13:39:18.883879   31797 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
oct. 23 13:39:18 raspberrypi k3s[31797]: I1023 13:39:18.945027   31797 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,Servic
oct. 23 13:39:18 raspberrypi k3s[31797]: I1023 13:39:18.945121   31797 plugins.go:161] Loaded 7 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,Priority,
oct. 23 13:39:18 raspberrypi k3s[31797]: time="2019-10-23T13:39:18.984369997+02:00" level=info msg="Running kube-scheduler --bind-address=127.0.0.1 --kubeconfig=/var/lib/rancher/k3s/server/cred/scheduler.
oct. 23 13:39:18 raspberrypi k3s[31797]: time="2019-10-23T13:39:18.984429060+02:00" level=info msg="Running kube-controller-manager --allocate-node-cidrs=true --bind-address=127.0.0.1 --cluster-cidr=10.42
oct. 23 13:39:19 raspberrypi k3s[31797]: I1023 13:39:19.038942   31797 server.go:143] Version: v1.16.2-k3s.1
oct. 23 13:39:19 raspberrypi k3s[31797]: I1023 13:39:19.039376   31797 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
oct. 23 13:39:19 raspberrypi k3s[31797]: I1023 13:39:19.040885   31797 controllermanager.go:161] Version: v1.16.2-k3s.1
oct. 23 13:39:19 raspberrypi k3s[31797]: W1023 13:39:19.047504   31797 authorization.go:47] Authorization is disabled
oct. 23 13:39:19 raspberrypi k3s[31797]: W1023 13:39:19.047576   31797 authentication.go:79] Authentication is disabled
oct. 23 13:39:19 raspberrypi k3s[31797]: I1023 13:39:19.047625   31797 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
oct. 23 13:39:19 raspberrypi k3s[31797]: I1023 13:39:19.050229   31797 deprecated_insecure_serving.go:53] Serving insecurely on [::]:10252
 ESCOD
oct. 23 13:39:15 raspberrypi systemd[1]: k3s.service: Service hold-off time over, scheduling restart.
oct. 23 13:39:15 raspberrypi systemd[1]: Stopped Lightweight Kubernetes.
-- Subject: L'unité (unit) k3s.service a terminé son arrêt
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- L'unité (unit) k3s.service a terminé son arrêt.
oct. 23 13:39:15 raspberrypi systemd[1]: Starting Lightweight Kubernetes...
-- Subject: L'unité (unit) k3s.service a commencé à démarrer
-- Defined-By: systemd
-- Support: https://www.debian.org/support`

`df -h
Sys. de fichiers Taille Utilisé Dispo Uti% Monté sur
/dev/root           13G    4,9G  7,5G  40% /
devtmpfs           458M       0  458M   0% /dev
tmpfs              462M       0  462M   0% /dev/shm
tmpfs              462M     47M  415M  11% /run
tmpfs              5,0M    4,0K  5,0M   1% /run/lock
tmpfs              462M       0  462M   0% /sys/fs/cgroup
/dev/mmcblk0p6      65M     21M   45M  33% /boot
tmpfs               93M       0   93M   0% /run/user/1000`

`uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`

I hope it helps.

**Comment by davidnuzik** [comment]
@gosuri if the issue is still happening please let us know and see Erik's comment. The issue can be reopened if necessary.

**Comment by AlaaAttya** [comment]
i'm having the same issue on pi4 8gb `Linux raspberrypi 5.10.17-v8+ #1414 SMP PREEMPT Fri Apr 30 13:23:25 BST 2021 aarch64 GNU/Linux`

**Comment by berlwein** [comment]
Same issue on a pi400. with Ubuntu 21.10 (64bit). The script exits with no error message, but k3s fails to install.  I have tried the install both with and without docker.

**Comment by brandond** [comment]
This indicates that your node is unable to curl the requested file. You can try curling the last displayed URL manually to see why it's failing.
